AllCops:
  NewCops: enable
  Exclude:
    - app/repl.rb

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics:
  Enabled: false

Style/Documentation:
  Exclude:
    - app/pacman/render/*
    - app/pacman/scenes/*

Style/FormatString:
  EnforcedStyle: percent

# Not DragonRuby supported
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# DragonRuby requires file extension
Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
